Adds jupyter notebook version of multi-ship loading sample, plus a readme
microsoft/qio-samples pull request #8
Opened 2021-03-09 12:38 UTC by frtibble

2021-03-19 18:28 UTC, anraman commented
@frtibble it would also be good to add a link to this new sample on the homepage readme where the other samples are listed

2021-03-22 11:17 UTC, frtibble commented
> @frtibble it would also be good to add a link to this new sample on the homepage readme where the other samples are listed

Done!

2021-03-26 01:41 UTC, ffrachon commented
All looks good to me at this point!

2021-03-26 01:41 UTC, ffrachon submitted a review, later dismissed

2021-03-26 19:03 UTC, anraman requested changes
I am going to create a PR from my own branch into this PR branch to address some of the larger changes to the maths in the first section as it will be a lot easier to review that way. If you agree with the minor code changes I have suggested, it would also be good to add these modifications to the python script.

2021-03-26 19:03 UTC, anraman commented on samples/multiship-loading-sample/README.md
> +Before approaching this sample, it is recommended that you complete the ship-loading sample, which can be found in this repository.
Would be good to link to the folder with the ship loading sample :)

2021-03-30 11:55 UTC, frtibble commented
Thanks @anraman - ready for your review

2021-03-30 18:51 UTC, anraman approved these changes

2021-03-30 18:52 UTC, merged